const mongoose = require('mongoose');
const reviewSchema2 = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  username: String,
  comment: String,
  createdAt: { type: Date, default: Date.now }
});


const laptopSchema = new mongoose.Schema({
  reviews: [reviewSchema2],
  trending:String,
  Imgurl: String,
  Product_name: String,
  Rating: Number,
  Price: Number,
  Release_date: String,
  Series: String,
  Weight: String,
  Colours: String,
  Battery_capacity: String,
  Material: String,
  Operating_system: String,
  Battery_Life: String,
  Processor: String,
  Size: String,
  Resolution: String,
  Touch_screen: String,
  Refresh_rate: String,
  RAM: String,
  Graphics_processor: String,
  Dedicated_graphics: String,
  SSD: String,
  Hard_disk: String,
  WiFi_standards_supported: String,
  Bluetooth_version: String,
  Web_camera: String,
  Backlit_keyboard: String,
  Speakers: String,
  Pointer_device: String,
  Internal_mic: String,
  Finger_print_sensor: String,
  Geekbench_single_core: String,
  Geekbench_multi_core: String,
  Cinebench_single_core: String,
  Cinebench_multi_core: String,
  GPU_base_clock: String,
  GPU_boost_clock: String,
  FLOPS: String,
  Memory_speed: String,
  Shading_units_cores: String,
  Pros: [String],
  Cons: [String],
  Category: String,
  Filter_brand: String,
  Filter_processor: String,
  Filter_display: String,
  Filter_os: String,
  Filter_release_date: Date,
  Filter_key_pref: [String],
  Filter_prof_tags: [String],
  Product_filter_display: String,
  Product_filter_processor: String,
  Product_filter_graphics: String,
  Product_filter_wifi: String,
  Product_filter_warranty: String,
  Yt_review: String,
  Amazon_link: String,
  Flipkart_link: String,
  Track_price: String,
});

module.exports = mongoose.model('laptopProduct', laptopSchema);