const mongoose = require('mongoose');

const phoneSchema = new mongoose.Schema({
  Imgurl:String,
  Product_name: String,

  Display_type: String,
  Display_size: String,
  Display_resolution: String,
  Aspect_ratio: String,
  PPI: String,
  Refresh_rate: String,
  Adaptive_refresh_rate: String,
  Max_rated_brightness: String,
  Max_rated_brightness_in_HDR: String,
  HDR_support: String,
  Touch_sampling_rate: String,
  Screen_protection: String,
  Screen_to_body_ratio: String,
  Display_features: [String],
  RGB_color_space: String,
  PWM: String,
  Response_time: String,
  Contrast: String,

  Height: String,
  Width: String,
  Thickness: String,
  Weight: String,
  Waterproof: String,
  Advanced_cooling: String,
  Rear_material: String,
  Frame_material: String,
  Colors: String,
  Fingerprint_scanner: String,

  RAM_size: String,
  Memory_type_RAM: String,
  Memory_clock_RAM: String,
  Channels_RAM: String,
  Storage_size_ROM: String,
  Storage_type_ROM: String,
  Memory_card: String,

  Operating_system: String,
  ROM: String,
  OS_size: String,

  Capacity: String,
  Max_charge_power: String,
  Battery_type: String,
  Replaceable: String,
  Wireless_charging: String,
  Reverse_charging: String,
  Fast_charging: String,
  Full_charging_time: String,
  Web_browsing: String,
  Watching_video: String,
  Gaming: String,
  Standby: String,

  WiFi_standard: String,
  WiFi_features: [String],
  Bluetooth_version: String,
  Bluetooth_features: String,
  USB_type: String,
  USB_version: String,
  USB_features: [String],
  DisplayPort: String,

  GPS: String,
  NFC: String,
  Infrared_port: String,
  Speakers: String,
  Headphone_audio_jack: String,
  FM_radio: String,
  Dolby_Atmos: String,

  Main_Matrix: String,
  Main_Image_resolution: String,
  Main_Zoom: String,
  Main_Flash: String,
  Main_Stabilization: String,
  Main_eightk_video_recording: String,
  Main_fourk_video_recording: String,
  Main_ten_eighty_p_video_recording: String,
  Main_Slow_motion: String,
  Main_Angle_of_widest_lens: String,
  Main_Lenses: [String],
  Main_Camera_features: [String],
  Camera_lens: [String],
  Lens_info: [
    mongoose.Schema.Types.Mixed
  ],

  Selfie_Megapixels: String,
  Selfie_Image_resolution: String,
  Selfie_Aperture: String,
  Selfie_Focal_length: String,
  Selfie_Sensor: String,
  Selfie_Sensor_size: String,
  Selfie_Pixel_size: String,
  Selfie_Autofocus: String,
  Selfie_Stabilization: String,
  Selfie_Video_resolution: String,
  Selfie_Depth_sensor_TOF: String,

  Soc_Chipset: String,
  Soc_Max_clock: String,
  Soc_CPU_cores: String,
  Soc_Architecture: [String],
  Soc_Manufacturing: String,
  Soc_Lithography_process: String,
  Soc_Neural_processor_NPU: String,
  Soc_Graphics: String,
  Soc_GPU_shading_units: String,
  Soc_GPU_clock: String,
  Soc_FLOPS: String,

  Benchmark_Geekbench_Compute_GPU: String,
  Benchmark_Single_core_score: String,
  Benchmark_Multi_core_score: String,
  Benchmark_AnTuTu_Benchmark_CPU: String,
  Benchmark_AnTuTu_Benchmark_GPU: String,
  Benchmark_AnTuTu_Benchmark_Memory: String,
  Benchmark_AnTuTu_Benchmark_UX: String,
  Benchmark_Total_score_AnTuTu_Benchmark: String,

  Highlight_Category: String,
  Highlight_Announced: String,
  Highlight_Release_date: String,

  Pros: [String],
  Cons: [String],

  Amazon_link: String,
  Flipkart_link: String,
});

const PhoneCompare = mongoose.model('PhoneCompare', phoneSchema);
module.exports = PhoneCompare;
